/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.smarthome.server.smartmeter;

import com.smarthome.battery.BatteryMode;
import com.smarthome.battery.ChargingStatus;
/**
 *
 * @author Adriana Dinelly - ID 25165771
 * 
 * This class stores consolidated information about the monitored house.
 * For now, it contains both the currently implemented data 
 * and placeholders for future integration with the other services.
 * 
 */
public class SmartMeterData {

    // ============= Basic Information =============

    // Stores the unique identifier of the monitored house.
    private String houseId;

    // ============= Solar Information =============

    // Stores the current solar energy production.
    private double currentSolarProduction;
    // Stores the production measurement unit (e.g. kWh).
    private String productionUnit;

    // ============= Battery Information =============

    // Stores the current battery level.
    private int batteryLevel;
    // Stores the current battery charging status.
    private ChargingStatus chargingStatus;
    // Stores the current battery mode.
    private BatteryMode batteryMode;

    // ============= Consumption Statistics =============

    // Stores the total energy consumption.
    private int totalConsumption;
    // Stores the average appliance consumption.
    private double averageConsumption;
    // Stores the appliance with the highest consumption.
    private String highestConsumer;
    // Stores the highest consumption value.
    private int highestConsumption;

    // ============= Energy Analysis =============
    
    // Stores the calculated energy efficiency.
    private double energyEfficiency;
    // Stores the recommendation generated by the Smart Meter.
    private String recommendation;

    
    // Constructor - creates a SmartMeterData object with all available information.

    public SmartMeterData(String houseId, double currentSolarProduction, String productionUnit, int batteryLevel,
                          ChargingStatus chargingStatus, BatteryMode batteryMode, int totalConsumption, double averageConsumption,
                          String highestConsumer, int highestConsumption, double energyEfficiency, String recommendation) {
        this.houseId = houseId;
        this.currentSolarProduction = currentSolarProduction;
        this.productionUnit = productionUnit;
        this.batteryLevel = batteryLevel;
        this.chargingStatus = chargingStatus;
        this.batteryMode = batteryMode;
        this.totalConsumption = totalConsumption;
        this.averageConsumption = averageConsumption;
        this.highestConsumer = highestConsumer;
        this.highestConsumption = highestConsumption;
        this.energyEfficiency = energyEfficiency;
        this.recommendation = recommendation;
    }
    
    // Getters and Setters 

    public String getHouseId() {
        return houseId;
    }

    public void setHouseId(String houseId) {
        this.houseId = houseId;
    }

    public double getCurrentSolarProduction() {
        return currentSolarProduction;
    }

    public void setCurrentSolarProduction(double currentSolarProduction) {
        this.currentSolarProduction = currentSolarProduction;
    }

    public String getProductionUnit() {
        return productionUnit;
    }

    public void setProductionUnit(String productionUnit) {
        this.productionUnit = productionUnit;
    }

    public int getBatteryLevel() {
        return batteryLevel;
    }

    public void setBatteryLevel(int batteryLevel) {
        this.batteryLevel = batteryLevel;
    }

    public ChargingStatus getChargingStatus() {
        return chargingStatus;
    }

    public void setChargingStatus(ChargingStatus chargingStatus) {
        this.chargingStatus = chargingStatus;
    }

    public BatteryMode getBatteryMode() {
        return batteryMode;
    }

    public void setBatteryMode(BatteryMode batteryMode) {
        this.batteryMode = batteryMode;
    }

    public int getTotalConsumption() {
        return totalConsumption;
    }

    public void setTotalConsumption(int totalConsumption) {
        this.totalConsumption = totalConsumption;
    }

    public double getAverageConsumption() {
        return averageConsumption;
    }

    public void setAverageConsumption(double averageConsumption) {
        this.averageConsumption = averageConsumption;
    }

    public String getHighestConsumer() {
        return highestConsumer;
    }

    public void setHighestConsumer(String highestConsumer) {
        this.highestConsumer = highestConsumer;
    }

    public int getHighestConsumption() {
        return highestConsumption;
    }

    public void setHighestConsumption(int highestConsumption) {
        this.highestConsumption = highestConsumption;
    }

    public double getEnergyEfficiency() {
        return energyEfficiency;
    }

    public void setEnergyEfficiency(double energyEfficiency) {
        this.energyEfficiency = energyEfficiency;
    }

    public String getRecommendation() {
        return recommendation;
    }

    public void setRecommendation(String recommendation) {
        this.recommendation = recommendation;
    }

    // toString method
    @Override
    public String toString() {
        return "SmartMeterData{" + "houseId='" + houseId + '\'' + ", currentSolarProduction=" + currentSolarProduction +
                ", productionUnit='" + productionUnit + '\'' + ", batteryLevel=" + batteryLevel + ", chargingStatus=" + chargingStatus +
                ", batteryMode=" + batteryMode + ", totalConsumption=" + totalConsumption + ", averageConsumption=" + averageConsumption +
                ", highestConsumer='" + highestConsumer + '\'' + ", highestConsumption=" + highestConsumption +
                ", energyEfficiency=" + energyEfficiency + ", recommendation='" + recommendation + '\'' + '}';
    }
}
