/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.smarthome.server.smartmeter;

import com.smarthome.battery.BatteryMode;
import com.smarthome.battery.ChargingStatus;
import com.smarthome.smartmeter.ConsumptionReading;
import com.smarthome.smartmeter.ConsumptionSummary;
import com.smarthome.smartmeter.GenerateEnergyReportRequest;
import com.smarthome.smartmeter.ReportEntry;
import com.smarthome.smartmeter.SmartMeterServiceGrpc;

import java.util.ArrayList;

import io.grpc.stub.StreamObserver;
/**
 *
 * @author Adriana Dinelly - ID 25165771
 * 
 * Implements the Smart Meter gRPC service.
 * 
 */
public class SmartMeterServiceImpl extends SmartMeterServiceGrpc.SmartMeterServiceImplBase {
    // Stores the current internal state of the Smart Meter.
    private final SmartMeterData smartMeterData;

    /**
     * This constructor creates the service with sample data.
     * The values are temporary and will later be updated
     * through communication with the Solar and Battery services.
     */
    public SmartMeterServiceImpl() {
        smartMeterData = new SmartMeterData(
                // Basic Information
                "HOUSE001",
                // Solar Information (Future Integration)
                24.8,
                "kWh",
                // Battery Information (Future Integration)
                82,
                ChargingStatus.CHARGING,
                BatteryMode.NORMAL,
                // Consumption Statistics
                2450,
                612.5,
                "Air Conditioner",
                1400,
                // Energy Analysis
                91.4,
                "Reduce energy usage during peak hours."
        );
    }


    // ======== Server Streaming method implementation ===========
    // One request is received, and multiple ReportEntry messages are streamed back to the client, generating the energy report.
    @Override
    public void generateEnergyReport(GenerateEnergyReportRequest request, StreamObserver<ReportEntry> responseObserver) {
        // Future validation:
        // In future versions, the Smart Meter will validate if the requested house exists before generating the report.
        String requestedHouse = request.getHouseId();

        // Sends the current solar production.
        responseObserver.onNext(createReportEntry("Current Solar Production",
                smartMeterData.getCurrentSolarProduction() + " " + smartMeterData.getProductionUnit(),
                "Current energy produced by the solar panels."
        ));

        // Sends the battery level.
        responseObserver.onNext(createReportEntry("Battery Level", smartMeterData.getBatteryLevel() + "%",
                "Current battery charge level."
        ));

        // Sends the highest consuming appliance.
        responseObserver.onNext(createReportEntry("Highest Consumer", smartMeterData.getHighestConsumer(),
                "Appliance with the highest energy consumption."
        ));

        // Sends the calculated energy efficiency.
        responseObserver.onNext(createReportEntry("Energy Efficiency", smartMeterData.getEnergyEfficiency() + "%",
                "Overall home energy efficiency."
        ));

        // Sends the Smart Meter recommendation.
        responseObserver.onNext(createReportEntry("Recommendation", smartMeterData.getRecommendation(),
                "Recommendation generated by the Smart Meter."
        ));

        // Indicates that no more report entries will be sent.
        responseObserver.onCompleted();
    }


    // Creates one report section. This helper method avoids repeating the Builder code.
    private ReportEntry createReportEntry(String section, String value, String description) {
        return ReportEntry.newBuilder().setSection(section).setValue(value).setDescription(description).build();
    }

    // ======== Client Streaming method implementation ========
    @Override
    public StreamObserver<ConsumptionReading> uploadConsumptionReadings(StreamObserver<ConsumptionSummary> responseObserver) {
        
        // Creates an ArrayList to store all received comsumption readings.
        ArrayList<ConsumptionReading> readings = new ArrayList<>();
        
        // We need to return a StreamObserver, which will be responsible for observing all the streamed messages from the client
        return new StreamObserver<ConsumptionReading>() {

            @Override
            public void onNext(ConsumptionReading reading) {
                // Stores each reading received from the client
                readings.add(reading);
            }

            @Override
            public void onError(Throwable t) {
                // prints an error message
                System.err.println("Streaming error: " + t.getMessage());
            }

            // This method will calculate the response after the client finishes sending information
            @Override
            public void onCompleted() {
                
                int totalConsumption = 0;
                int highestConsumption = Integer.MIN_VALUE;
                String highestConsumer = "";

                for (ConsumptionReading reading : readings) {
                    totalConsumption += reading.getConsumption();
                    
                    if (reading.getConsumption() > highestConsumption) {
                        highestConsumption = reading.getConsumption();
                        highestConsumer = reading.getDevice();

                    }
                }
                // calculating the average consumption
                double averageConsumption;
                
                if(readings.isEmpty()) {
                    averageConsumption = 0;
                } else {
                    averageConsumption = (double) totalConsumption / readings.size();
                }
                
            // Updates the Smart Meter internal state.
            smartMeterData.setTotalConsumption(totalConsumption);
            smartMeterData.setAverageConsumption(averageConsumption);
            smartMeterData.setHighestConsumer(highestConsumer);
            smartMeterData.setHighestConsumption(highestConsumption);

            // building the consumption summary to send back to the client
            ConsumptionSummary summary = ConsumptionSummary.newBuilder().setHighestConsumer(highestConsumer)
                            .setHighestConsumption(highestConsumption).setTotalConsumption(totalConsumption)
                            .setAverageConsumption(averageConsumption).build();

            // Only one onNext because the client streaming answers only once
            responseObserver.onNext(summary);
            // Communicates the end of the response
            responseObserver.onCompleted();
            
            }
        };
    }
}
