/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.smarthome.gui;

import com.smarthome.integrationclient.SolarGrpcClient;
import com.smarthome.solar.ProductionInfo;
import com.smarthome.solar.ProductionInfo;
import io.grpc.stub.StreamObserver;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Adriana
 */
public class SmartHomeGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SmartHomeGUI.class.getName());

    // Internal client responsible for communicating with the Solar Panel Service.
    private final SolarGrpcClient solarClient;
    
    /**
     * Creates new form MainGUI
     */
    public SmartHomeGUI() {
        initComponents();
        // Initializes the client
        solarClient = new SolarGrpcClient();
        // Set main window location to centralize it
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        solarPanelTab = new javax.swing.JPanel();
        solarPanelLabel = new java.awt.Label();
        panelIdLabel = new java.awt.Label();
        txtSolarPanelId = new java.awt.TextField();
        btnGetProduction = new javax.swing.JButton();
        btnMonitorProduction = new javax.swing.JToggleButton();
        productionResultLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSolarResults = new javax.swing.JTextArea();
        batteryPanelTab = new javax.swing.JPanel();
        batteryStorageLabel = new java.awt.Label();
        smartMeterTab = new javax.swing.JPanel();
        smartMeterLabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Home Energy Management System");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(750, 550));

        solarPanelLabel.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        solarPanelLabel.setText("Solar Panel Service");

        panelIdLabel.setText("Panel ID:");

        txtSolarPanelId.setText("SP-001");

        btnGetProduction.setText("Get Current Production");
        btnGetProduction.addActionListener(this::btnGetProductionActionPerformed);

        btnMonitorProduction.setText("Start Monitoring Production");
        btnMonitorProduction.addActionListener(this::btnMonitorProductionActionPerformed);

        productionResultLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        productionResultLabel.setText("Results");

        txtSolarResults.setColumns(20);
        txtSolarResults.setRows(5);
        txtSolarResults.setText("Energy production results will be shown here...");
        jScrollPane1.setViewportView(txtSolarResults);

        javax.swing.GroupLayout solarPanelTabLayout = new javax.swing.GroupLayout(solarPanelTab);
        solarPanelTab.setLayout(solarPanelTabLayout);
        solarPanelTabLayout.setHorizontalGroup(
            solarPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solarPanelTabLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(solarPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(solarPanelLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(solarPanelTabLayout.createSequentialGroup()
                        .addGroup(solarPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productionResultLabel)
                            .addGroup(solarPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnMonitorProduction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                .addComponent(btnGetProduction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(solarPanelTabLayout.createSequentialGroup()
                        .addComponent(txtSolarPanelId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        solarPanelTabLayout.setVerticalGroup(
            solarPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solarPanelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(solarPanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtSolarPanelId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGetProduction)
                .addGap(18, 18, 18)
                .addComponent(btnMonitorProduction)
                .addGap(38, 38, 38)
                .addComponent(productionResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        solarPanelLabel.getAccessibleContext().setAccessibleName("Solar Panel Service");
        solarPanelLabel.getAccessibleContext().setAccessibleDescription("");

        tabbedPane.addTab("Solar Panel", solarPanelTab);

        batteryStorageLabel.setAlignment(java.awt.Label.CENTER);
        batteryStorageLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        batteryStorageLabel.setText("Battery Storage Service");

        javax.swing.GroupLayout batteryPanelTabLayout = new javax.swing.GroupLayout(batteryPanelTab);
        batteryPanelTab.setLayout(batteryPanelTabLayout);
        batteryPanelTabLayout.setHorizontalGroup(
            batteryPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, batteryPanelTabLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(batteryStorageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
        );
        batteryPanelTabLayout.setVerticalGroup(
            batteryPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(batteryPanelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(batteryStorageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Battery Storage", batteryPanelTab);

        smartMeterLabel.setAlignment(java.awt.Label.CENTER);
        smartMeterLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        smartMeterLabel.setText("Smart Meter Service");

        javax.swing.GroupLayout smartMeterTabLayout = new javax.swing.GroupLayout(smartMeterTab);
        smartMeterTab.setLayout(smartMeterTabLayout);
        smartMeterTabLayout.setHorizontalGroup(
            smartMeterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smartMeterTabLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(smartMeterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );
        smartMeterTabLayout.setVerticalGroup(
            smartMeterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smartMeterTabLayout.createSequentialGroup()
                .addComponent(smartMeterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(0, 387, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Smart Meter", smartMeterTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetProductionActionPerformed
        // Retrieve the Panel ID entered by the user.
        String panelId = txtSolarPanelId.getText().trim();

        // Check whether the Panel ID field is empty.
        if (panelId.isBlank()) {

            // Display an error message requesting a valid Panel ID.
            JOptionPane.showMessageDialog(this, "Please enter a Panel ID.", "Missing Panel ID", JOptionPane.WARNING_MESSAGE);

            // Stop the execution of the method.
            return;
        }

        // Display a temporary message while waiting for the server response.
        txtSolarResults.setText("Loading current production data...");

        try {

            // Invoke the Unary RPC through the internal Solar gRPC client.
            ProductionInfo productionInfo = solarClient.getCurrentProduction(panelId);

            // Format the response in a user-friendly way.
            String result =
                    "Current Production Information\n"
                    + "----------------------------------------\n"
                    + "Panel ID: " + panelId + "\n\n"
                    + "Current Production: " + productionInfo.getCurrentProduction() + " W\n";

            // Display the formatted result.
            txtSolarResults.setText(result);

        } catch (Exception e) {

            // Display the error message if the RPC invocation fails.
            txtSolarResults.setText("Unable to retrieve the current production.\n\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnGetProductionActionPerformed

    private void btnMonitorProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorProductionActionPerformed
        // Retrieve the Panel ID entered by the user.
        String panelId = txtSolarPanelId.getText().trim();

        // Check whether the Panel ID field is empty.
        if (panelId.isBlank()) {

            // Display a warning message.
            JOptionPane.showMessageDialog(this, "Please enter a Panel ID.", "Missing Panel ID", JOptionPane.WARNING_MESSAGE);

            // Restore the ToggleButton state.
            btnMonitorProduction.setSelected(false);

            return;
        }

        // Check whether the monitoring should start or stop.
        if (btnMonitorProduction.isSelected()) {

            // Update the button text.
            btnMonitorProduction.setText("Stop Monitoring");
            // Clear previous results.
            txtSolarResults.setText("");
            // Display a status message.
            txtSolarResults.append("Monitoring started...\n\n");
            // Start the Server Streaming RPC.
            solarClient.monitorProduction(panelId, new StreamObserver<ProductionInfo>() {

                @Override
                public void onNext(ProductionInfo productionInfo) {

                    // Update the GUI on the Swing Event Dispatch Thread.
                    SwingUtilities.invokeLater(() -> {

                        txtSolarResults.append(
                                "Timestamp: " + productionInfo.getTimestamp() + "\n"
                                + "Current Production: " + productionInfo.getCurrentProduction() + " " + productionInfo.getUnit() + "\n\n");
                    });
                }

                @Override
                public void onError(Throwable throwable) {

                    // Update the GUI on the Swing Event Dispatch Thread.
                    SwingUtilities.invokeLater(() -> {

                        txtSolarResults.append("Monitoring stopped.\n" + throwable.getMessage() + "\n");

                        // Restore the ToggleButton.
                        btnMonitorProduction.setSelected(false);
                        btnMonitorProduction.setText("Monitor Production");
                    });
                }

                @Override
                public void onCompleted() {

                    // Update the GUI on the Swing Event Dispatch Thread.
                    SwingUtilities.invokeLater(() -> {

                        txtSolarResults.append("Monitoring completed.\n");

                        // Restore the ToggleButton.
                        btnMonitorProduction.setSelected(false);
                        btnMonitorProduction.setText("Monitor Production");

                    });
                }
            });
            
        } else {

            // Stop the monitoring stream.
            solarClient.stopMonitoring();
            // Inform the user.
            txtSolarResults.append("\nMonitoring cancelled by the user.\n");
            // Restore the button text.
            btnMonitorProduction.setText("Monitor Production");
        }
    }//GEN-LAST:event_btnMonitorProductionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SmartHomeGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel batteryPanelTab;
    private java.awt.Label batteryStorageLabel;
    private javax.swing.JButton btnGetProduction;
    private javax.swing.JToggleButton btnMonitorProduction;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label panelIdLabel;
    private javax.swing.JLabel productionResultLabel;
    private java.awt.Label smartMeterLabel;
    private javax.swing.JPanel smartMeterTab;
    private java.awt.Label solarPanelLabel;
    private javax.swing.JPanel solarPanelTab;
    private javax.swing.JTabbedPane tabbedPane;
    private java.awt.TextField txtSolarPanelId;
    private javax.swing.JTextArea txtSolarResults;
    // End of variables declaration//GEN-END:variables
}
