// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

/**
 * Protobuf type {@code battery.BatteryMonitoringRequest}
 */
public  final class BatteryMonitoringRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:battery.BatteryMonitoringRequest)
    BatteryMonitoringRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatteryMonitoringRequest.newBuilder() to construct.
  private BatteryMonitoringRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatteryMonitoringRequest() {
    batteryId_ = "";
    command_ = 0;
    mode_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatteryMonitoringRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            batteryId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            mode_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.battery.BatteryMonitoringRequest.class, com.smarthome.battery.BatteryMonitoringRequest.Builder.class);
  }

  public static final int BATTERYID_FIELD_NUMBER = 1;
  private volatile java.lang.Object batteryId_;
  /**
   * <pre>
   * Sends which battery is being monitored.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  public java.lang.String getBatteryId() {
    java.lang.Object ref = batteryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batteryId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Sends which battery is being monitored.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBatteryIdBytes() {
    java.lang.Object ref = batteryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batteryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 2;
  private int command_;
  /**
   * <pre>
   * Command issued by the GUI.
   * </pre>
   *
   * <code>.battery.BatteryCommand command = 2;</code>
   */
  public int getCommandValue() {
    return command_;
  }
  /**
   * <pre>
   * Command issued by the GUI.
   * </pre>
   *
   * <code>.battery.BatteryCommand command = 2;</code>
   */
  public com.smarthome.battery.BatteryCommand getCommand() {
    @SuppressWarnings("deprecation")
    com.smarthome.battery.BatteryCommand result = com.smarthome.battery.BatteryCommand.valueOf(command_);
    return result == null ? com.smarthome.battery.BatteryCommand.UNRECOGNIZED : result;
  }

  public static final int MODE_FIELD_NUMBER = 3;
  private int mode_;
  /**
   * <pre>
   * Operating mode selected by the user.
   * This field is mainly used together with CHANGE_MODE.
   * </pre>
   *
   * <code>.battery.BatteryMode mode = 3;</code>
   */
  public int getModeValue() {
    return mode_;
  }
  /**
   * <pre>
   * Operating mode selected by the user.
   * This field is mainly used together with CHANGE_MODE.
   * </pre>
   *
   * <code>.battery.BatteryMode mode = 3;</code>
   */
  public com.smarthome.battery.BatteryMode getMode() {
    @SuppressWarnings("deprecation")
    com.smarthome.battery.BatteryMode result = com.smarthome.battery.BatteryMode.valueOf(mode_);
    return result == null ? com.smarthome.battery.BatteryMode.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBatteryIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, batteryId_);
    }
    if (command_ != com.smarthome.battery.BatteryCommand.START.getNumber()) {
      output.writeEnum(2, command_);
    }
    if (mode_ != com.smarthome.battery.BatteryMode.NORMAL.getNumber()) {
      output.writeEnum(3, mode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBatteryIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, batteryId_);
    }
    if (command_ != com.smarthome.battery.BatteryCommand.START.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, command_);
    }
    if (mode_ != com.smarthome.battery.BatteryMode.NORMAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, mode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.battery.BatteryMonitoringRequest)) {
      return super.equals(obj);
    }
    com.smarthome.battery.BatteryMonitoringRequest other = (com.smarthome.battery.BatteryMonitoringRequest) obj;

    boolean result = true;
    result = result && getBatteryId()
        .equals(other.getBatteryId());
    result = result && command_ == other.command_;
    result = result && mode_ == other.mode_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATTERYID_FIELD_NUMBER;
    hash = (53 * hash) + getBatteryId().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    hash = (37 * hash) + MODE_FIELD_NUMBER;
    hash = (53 * hash) + mode_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryMonitoringRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.battery.BatteryMonitoringRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code battery.BatteryMonitoringRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:battery.BatteryMonitoringRequest)
      com.smarthome.battery.BatteryMonitoringRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.battery.BatteryMonitoringRequest.class, com.smarthome.battery.BatteryMonitoringRequest.Builder.class);
    }

    // Construct using com.smarthome.battery.BatteryMonitoringRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      batteryId_ = "";

      command_ = 0;

      mode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringRequest_descriptor;
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryMonitoringRequest getDefaultInstanceForType() {
      return com.smarthome.battery.BatteryMonitoringRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryMonitoringRequest build() {
      com.smarthome.battery.BatteryMonitoringRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryMonitoringRequest buildPartial() {
      com.smarthome.battery.BatteryMonitoringRequest result = new com.smarthome.battery.BatteryMonitoringRequest(this);
      result.batteryId_ = batteryId_;
      result.command_ = command_;
      result.mode_ = mode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.battery.BatteryMonitoringRequest) {
        return mergeFrom((com.smarthome.battery.BatteryMonitoringRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.battery.BatteryMonitoringRequest other) {
      if (other == com.smarthome.battery.BatteryMonitoringRequest.getDefaultInstance()) return this;
      if (!other.getBatteryId().isEmpty()) {
        batteryId_ = other.batteryId_;
        onChanged();
      }
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.mode_ != 0) {
        setModeValue(other.getModeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.battery.BatteryMonitoringRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.battery.BatteryMonitoringRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object batteryId_ = "";
    /**
     * <pre>
     * Sends which battery is being monitored.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public java.lang.String getBatteryId() {
      java.lang.Object ref = batteryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batteryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Sends which battery is being monitored.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBatteryIdBytes() {
      java.lang.Object ref = batteryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batteryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Sends which battery is being monitored.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public Builder setBatteryId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batteryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sends which battery is being monitored.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public Builder clearBatteryId() {
      
      batteryId_ = getDefaultInstance().getBatteryId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Sends which battery is being monitored.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public Builder setBatteryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batteryId_ = value;
      onChanged();
      return this;
    }

    private int command_ = 0;
    /**
     * <pre>
     * Command issued by the GUI.
     * </pre>
     *
     * <code>.battery.BatteryCommand command = 2;</code>
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <pre>
     * Command issued by the GUI.
     * </pre>
     *
     * <code>.battery.BatteryCommand command = 2;</code>
     */
    public Builder setCommandValue(int value) {
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Command issued by the GUI.
     * </pre>
     *
     * <code>.battery.BatteryCommand command = 2;</code>
     */
    public com.smarthome.battery.BatteryCommand getCommand() {
      @SuppressWarnings("deprecation")
      com.smarthome.battery.BatteryCommand result = com.smarthome.battery.BatteryCommand.valueOf(command_);
      return result == null ? com.smarthome.battery.BatteryCommand.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Command issued by the GUI.
     * </pre>
     *
     * <code>.battery.BatteryCommand command = 2;</code>
     */
    public Builder setCommand(com.smarthome.battery.BatteryCommand value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Command issued by the GUI.
     * </pre>
     *
     * <code>.battery.BatteryCommand command = 2;</code>
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private int mode_ = 0;
    /**
     * <pre>
     * Operating mode selected by the user.
     * This field is mainly used together with CHANGE_MODE.
     * </pre>
     *
     * <code>.battery.BatteryMode mode = 3;</code>
     */
    public int getModeValue() {
      return mode_;
    }
    /**
     * <pre>
     * Operating mode selected by the user.
     * This field is mainly used together with CHANGE_MODE.
     * </pre>
     *
     * <code>.battery.BatteryMode mode = 3;</code>
     */
    public Builder setModeValue(int value) {
      mode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operating mode selected by the user.
     * This field is mainly used together with CHANGE_MODE.
     * </pre>
     *
     * <code>.battery.BatteryMode mode = 3;</code>
     */
    public com.smarthome.battery.BatteryMode getMode() {
      @SuppressWarnings("deprecation")
      com.smarthome.battery.BatteryMode result = com.smarthome.battery.BatteryMode.valueOf(mode_);
      return result == null ? com.smarthome.battery.BatteryMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Operating mode selected by the user.
     * This field is mainly used together with CHANGE_MODE.
     * </pre>
     *
     * <code>.battery.BatteryMode mode = 3;</code>
     */
    public Builder setMode(com.smarthome.battery.BatteryMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      mode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operating mode selected by the user.
     * This field is mainly used together with CHANGE_MODE.
     * </pre>
     *
     * <code>.battery.BatteryMode mode = 3;</code>
     */
    public Builder clearMode() {
      
      mode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:battery.BatteryMonitoringRequest)
  }

  // @@protoc_insertion_point(class_scope:battery.BatteryMonitoringRequest)
  private static final com.smarthome.battery.BatteryMonitoringRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.battery.BatteryMonitoringRequest();
  }

  public static com.smarthome.battery.BatteryMonitoringRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatteryMonitoringRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatteryMonitoringRequest>() {
    @java.lang.Override
    public BatteryMonitoringRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatteryMonitoringRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatteryMonitoringRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatteryMonitoringRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.battery.BatteryMonitoringRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

