// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

public interface BatteryMonitoringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:battery.BatteryMonitoringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Sends which battery is being monitored.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  java.lang.String getBatteryId();
  /**
   * <pre>
   * Sends which battery is being monitored.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatteryIdBytes();

  /**
   * <pre>
   * Command issued by the GUI.
   * </pre>
   *
   * <code>.battery.BatteryCommand command = 2;</code>
   */
  int getCommandValue();
  /**
   * <pre>
   * Command issued by the GUI.
   * </pre>
   *
   * <code>.battery.BatteryCommand command = 2;</code>
   */
  com.smarthome.battery.BatteryCommand getCommand();

  /**
   * <pre>
   * Operating mode selected by the user.
   * This field is mainly used together with CHANGE_MODE.
   * </pre>
   *
   * <code>.battery.BatteryMode mode = 3;</code>
   */
  int getModeValue();
  /**
   * <pre>
   * Operating mode selected by the user.
   * This field is mainly used together with CHANGE_MODE.
   * </pre>
   *
   * <code>.battery.BatteryMode mode = 3;</code>
   */
  com.smarthome.battery.BatteryMode getMode();
}
