// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

/**
 * Protobuf type {@code battery.BatteryStatusInfo}
 */
public  final class BatteryStatusInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:battery.BatteryStatusInfo)
    BatteryStatusInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatteryStatusInfo.newBuilder() to construct.
  private BatteryStatusInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatteryStatusInfo() {
    batteryId_ = "";
    batteryLevel_ = 0;
    chargingStatus_ = 0;
    currentMode_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatteryStatusInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            batteryId_ = s;
            break;
          }
          case 16: {

            batteryLevel_ = input.readInt32();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            chargingStatus_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            currentMode_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryStatusInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryStatusInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.battery.BatteryStatusInfo.class, com.smarthome.battery.BatteryStatusInfo.Builder.class);
  }

  public static final int BATTERYID_FIELD_NUMBER = 1;
  private volatile java.lang.Object batteryId_;
  /**
   * <pre>
   * Battery identifier.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  public java.lang.String getBatteryId() {
    java.lang.Object ref = batteryId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batteryId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Battery identifier.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBatteryIdBytes() {
    java.lang.Object ref = batteryId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batteryId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BATTERYLEVEL_FIELD_NUMBER = 2;
  private int batteryLevel_;
  /**
   * <pre>
   * Current battery level (percentage).
   * </pre>
   *
   * <code>int32 batteryLevel = 2;</code>
   */
  public int getBatteryLevel() {
    return batteryLevel_;
  }

  public static final int CHARGINGSTATUS_FIELD_NUMBER = 3;
  private int chargingStatus_;
  /**
   * <pre>
   * Current charging status.
   * </pre>
   *
   * <code>.battery.ChargingStatus chargingStatus = 3;</code>
   */
  public int getChargingStatusValue() {
    return chargingStatus_;
  }
  /**
   * <pre>
   * Current charging status.
   * </pre>
   *
   * <code>.battery.ChargingStatus chargingStatus = 3;</code>
   */
  public com.smarthome.battery.ChargingStatus getChargingStatus() {
    @SuppressWarnings("deprecation")
    com.smarthome.battery.ChargingStatus result = com.smarthome.battery.ChargingStatus.valueOf(chargingStatus_);
    return result == null ? com.smarthome.battery.ChargingStatus.UNRECOGNIZED : result;
  }

  public static final int CURRENTMODE_FIELD_NUMBER = 4;
  private int currentMode_;
  /**
   * <pre>
   * Current operating mode.
   * </pre>
   *
   * <code>.battery.BatteryMode currentMode = 4;</code>
   */
  public int getCurrentModeValue() {
    return currentMode_;
  }
  /**
   * <pre>
   * Current operating mode.
   * </pre>
   *
   * <code>.battery.BatteryMode currentMode = 4;</code>
   */
  public com.smarthome.battery.BatteryMode getCurrentMode() {
    @SuppressWarnings("deprecation")
    com.smarthome.battery.BatteryMode result = com.smarthome.battery.BatteryMode.valueOf(currentMode_);
    return result == null ? com.smarthome.battery.BatteryMode.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBatteryIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, batteryId_);
    }
    if (batteryLevel_ != 0) {
      output.writeInt32(2, batteryLevel_);
    }
    if (chargingStatus_ != com.smarthome.battery.ChargingStatus.UNKNOWN.getNumber()) {
      output.writeEnum(3, chargingStatus_);
    }
    if (currentMode_ != com.smarthome.battery.BatteryMode.NORMAL.getNumber()) {
      output.writeEnum(4, currentMode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBatteryIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, batteryId_);
    }
    if (batteryLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, batteryLevel_);
    }
    if (chargingStatus_ != com.smarthome.battery.ChargingStatus.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, chargingStatus_);
    }
    if (currentMode_ != com.smarthome.battery.BatteryMode.NORMAL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, currentMode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.battery.BatteryStatusInfo)) {
      return super.equals(obj);
    }
    com.smarthome.battery.BatteryStatusInfo other = (com.smarthome.battery.BatteryStatusInfo) obj;

    boolean result = true;
    result = result && getBatteryId()
        .equals(other.getBatteryId());
    result = result && (getBatteryLevel()
        == other.getBatteryLevel());
    result = result && chargingStatus_ == other.chargingStatus_;
    result = result && currentMode_ == other.currentMode_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BATTERYID_FIELD_NUMBER;
    hash = (53 * hash) + getBatteryId().hashCode();
    hash = (37 * hash) + BATTERYLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getBatteryLevel();
    hash = (37 * hash) + CHARGINGSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + chargingStatus_;
    hash = (37 * hash) + CURRENTMODE_FIELD_NUMBER;
    hash = (53 * hash) + currentMode_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryStatusInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.battery.BatteryStatusInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code battery.BatteryStatusInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:battery.BatteryStatusInfo)
      com.smarthome.battery.BatteryStatusInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryStatusInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryStatusInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.battery.BatteryStatusInfo.class, com.smarthome.battery.BatteryStatusInfo.Builder.class);
    }

    // Construct using com.smarthome.battery.BatteryStatusInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      batteryId_ = "";

      batteryLevel_ = 0;

      chargingStatus_ = 0;

      currentMode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryStatusInfo_descriptor;
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryStatusInfo getDefaultInstanceForType() {
      return com.smarthome.battery.BatteryStatusInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryStatusInfo build() {
      com.smarthome.battery.BatteryStatusInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryStatusInfo buildPartial() {
      com.smarthome.battery.BatteryStatusInfo result = new com.smarthome.battery.BatteryStatusInfo(this);
      result.batteryId_ = batteryId_;
      result.batteryLevel_ = batteryLevel_;
      result.chargingStatus_ = chargingStatus_;
      result.currentMode_ = currentMode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.battery.BatteryStatusInfo) {
        return mergeFrom((com.smarthome.battery.BatteryStatusInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.battery.BatteryStatusInfo other) {
      if (other == com.smarthome.battery.BatteryStatusInfo.getDefaultInstance()) return this;
      if (!other.getBatteryId().isEmpty()) {
        batteryId_ = other.batteryId_;
        onChanged();
      }
      if (other.getBatteryLevel() != 0) {
        setBatteryLevel(other.getBatteryLevel());
      }
      if (other.chargingStatus_ != 0) {
        setChargingStatusValue(other.getChargingStatusValue());
      }
      if (other.currentMode_ != 0) {
        setCurrentModeValue(other.getCurrentModeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.battery.BatteryStatusInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.battery.BatteryStatusInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object batteryId_ = "";
    /**
     * <pre>
     * Battery identifier.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public java.lang.String getBatteryId() {
      java.lang.Object ref = batteryId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batteryId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Battery identifier.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBatteryIdBytes() {
      java.lang.Object ref = batteryId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batteryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Battery identifier.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public Builder setBatteryId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batteryId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Battery identifier.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public Builder clearBatteryId() {
      
      batteryId_ = getDefaultInstance().getBatteryId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Battery identifier.
     * </pre>
     *
     * <code>string batteryId = 1;</code>
     */
    public Builder setBatteryIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batteryId_ = value;
      onChanged();
      return this;
    }

    private int batteryLevel_ ;
    /**
     * <pre>
     * Current battery level (percentage).
     * </pre>
     *
     * <code>int32 batteryLevel = 2;</code>
     */
    public int getBatteryLevel() {
      return batteryLevel_;
    }
    /**
     * <pre>
     * Current battery level (percentage).
     * </pre>
     *
     * <code>int32 batteryLevel = 2;</code>
     */
    public Builder setBatteryLevel(int value) {
      
      batteryLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current battery level (percentage).
     * </pre>
     *
     * <code>int32 batteryLevel = 2;</code>
     */
    public Builder clearBatteryLevel() {
      
      batteryLevel_ = 0;
      onChanged();
      return this;
    }

    private int chargingStatus_ = 0;
    /**
     * <pre>
     * Current charging status.
     * </pre>
     *
     * <code>.battery.ChargingStatus chargingStatus = 3;</code>
     */
    public int getChargingStatusValue() {
      return chargingStatus_;
    }
    /**
     * <pre>
     * Current charging status.
     * </pre>
     *
     * <code>.battery.ChargingStatus chargingStatus = 3;</code>
     */
    public Builder setChargingStatusValue(int value) {
      chargingStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current charging status.
     * </pre>
     *
     * <code>.battery.ChargingStatus chargingStatus = 3;</code>
     */
    public com.smarthome.battery.ChargingStatus getChargingStatus() {
      @SuppressWarnings("deprecation")
      com.smarthome.battery.ChargingStatus result = com.smarthome.battery.ChargingStatus.valueOf(chargingStatus_);
      return result == null ? com.smarthome.battery.ChargingStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Current charging status.
     * </pre>
     *
     * <code>.battery.ChargingStatus chargingStatus = 3;</code>
     */
    public Builder setChargingStatus(com.smarthome.battery.ChargingStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      chargingStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current charging status.
     * </pre>
     *
     * <code>.battery.ChargingStatus chargingStatus = 3;</code>
     */
    public Builder clearChargingStatus() {
      
      chargingStatus_ = 0;
      onChanged();
      return this;
    }

    private int currentMode_ = 0;
    /**
     * <pre>
     * Current operating mode.
     * </pre>
     *
     * <code>.battery.BatteryMode currentMode = 4;</code>
     */
    public int getCurrentModeValue() {
      return currentMode_;
    }
    /**
     * <pre>
     * Current operating mode.
     * </pre>
     *
     * <code>.battery.BatteryMode currentMode = 4;</code>
     */
    public Builder setCurrentModeValue(int value) {
      currentMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current operating mode.
     * </pre>
     *
     * <code>.battery.BatteryMode currentMode = 4;</code>
     */
    public com.smarthome.battery.BatteryMode getCurrentMode() {
      @SuppressWarnings("deprecation")
      com.smarthome.battery.BatteryMode result = com.smarthome.battery.BatteryMode.valueOf(currentMode_);
      return result == null ? com.smarthome.battery.BatteryMode.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Current operating mode.
     * </pre>
     *
     * <code>.battery.BatteryMode currentMode = 4;</code>
     */
    public Builder setCurrentMode(com.smarthome.battery.BatteryMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      currentMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Current operating mode.
     * </pre>
     *
     * <code>.battery.BatteryMode currentMode = 4;</code>
     */
    public Builder clearCurrentMode() {
      
      currentMode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:battery.BatteryStatusInfo)
  }

  // @@protoc_insertion_point(class_scope:battery.BatteryStatusInfo)
  private static final com.smarthome.battery.BatteryStatusInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.battery.BatteryStatusInfo();
  }

  public static com.smarthome.battery.BatteryStatusInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatteryStatusInfo>
      PARSER = new com.google.protobuf.AbstractParser<BatteryStatusInfo>() {
    @java.lang.Override
    public BatteryStatusInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatteryStatusInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatteryStatusInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatteryStatusInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.battery.BatteryStatusInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

