// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

/**
 * Protobuf type {@code battery.BatteryMonitoringResponse}
 */
public  final class BatteryMonitoringResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:battery.BatteryMonitoringResponse)
    BatteryMonitoringResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatteryMonitoringResponse.newBuilder() to construct.
  private BatteryMonitoringResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatteryMonitoringResponse() {
    estimatedTimeRemaining_ = "";
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatteryMonitoringResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.smarthome.battery.BatteryStatusInfo.Builder subBuilder = null;
            if (batteryInfo_ != null) {
              subBuilder = batteryInfo_.toBuilder();
            }
            batteryInfo_ = input.readMessage(com.smarthome.battery.BatteryStatusInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(batteryInfo_);
              batteryInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            estimatedTimeRemaining_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.battery.BatteryMonitoringResponse.class, com.smarthome.battery.BatteryMonitoringResponse.Builder.class);
  }

  public static final int BATTERYINFO_FIELD_NUMBER = 1;
  private com.smarthome.battery.BatteryStatusInfo batteryInfo_;
  /**
   * <pre>
   * Current battery information.
   * </pre>
   *
   * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
   */
  public boolean hasBatteryInfo() {
    return batteryInfo_ != null;
  }
  /**
   * <pre>
   * Current battery information.
   * </pre>
   *
   * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
   */
  public com.smarthome.battery.BatteryStatusInfo getBatteryInfo() {
    return batteryInfo_ == null ? com.smarthome.battery.BatteryStatusInfo.getDefaultInstance() : batteryInfo_;
  }
  /**
   * <pre>
   * Current battery information.
   * </pre>
   *
   * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
   */
  public com.smarthome.battery.BatteryStatusInfoOrBuilder getBatteryInfoOrBuilder() {
    return getBatteryInfo();
  }

  public static final int ESTIMATEDTIMEREMAINING_FIELD_NUMBER = 2;
  private volatile java.lang.Object estimatedTimeRemaining_;
  /**
   * <pre>
   * Estimated remaining charging/discharging time.
   * </pre>
   *
   * <code>string estimatedTimeRemaining = 2;</code>
   */
  public java.lang.String getEstimatedTimeRemaining() {
    java.lang.Object ref = estimatedTimeRemaining_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      estimatedTimeRemaining_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Estimated remaining charging/discharging time.
   * </pre>
   *
   * <code>string estimatedTimeRemaining = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEstimatedTimeRemainingBytes() {
    java.lang.Object ref = estimatedTimeRemaining_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      estimatedTimeRemaining_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * Informational message describing the latest battery event (e.g. "Battery fully charged").
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Informational message describing the latest battery event (e.g. "Battery fully charged").
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (batteryInfo_ != null) {
      output.writeMessage(1, getBatteryInfo());
    }
    if (!getEstimatedTimeRemainingBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, estimatedTimeRemaining_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (batteryInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBatteryInfo());
    }
    if (!getEstimatedTimeRemainingBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, estimatedTimeRemaining_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.battery.BatteryMonitoringResponse)) {
      return super.equals(obj);
    }
    com.smarthome.battery.BatteryMonitoringResponse other = (com.smarthome.battery.BatteryMonitoringResponse) obj;

    boolean result = true;
    result = result && (hasBatteryInfo() == other.hasBatteryInfo());
    if (hasBatteryInfo()) {
      result = result && getBatteryInfo()
          .equals(other.getBatteryInfo());
    }
    result = result && getEstimatedTimeRemaining()
        .equals(other.getEstimatedTimeRemaining());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBatteryInfo()) {
      hash = (37 * hash) + BATTERYINFO_FIELD_NUMBER;
      hash = (53 * hash) + getBatteryInfo().hashCode();
    }
    hash = (37 * hash) + ESTIMATEDTIMEREMAINING_FIELD_NUMBER;
    hash = (53 * hash) + getEstimatedTimeRemaining().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.battery.BatteryMonitoringResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.battery.BatteryMonitoringResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code battery.BatteryMonitoringResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:battery.BatteryMonitoringResponse)
      com.smarthome.battery.BatteryMonitoringResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.battery.BatteryMonitoringResponse.class, com.smarthome.battery.BatteryMonitoringResponse.Builder.class);
    }

    // Construct using com.smarthome.battery.BatteryMonitoringResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (batteryInfoBuilder_ == null) {
        batteryInfo_ = null;
      } else {
        batteryInfo_ = null;
        batteryInfoBuilder_ = null;
      }
      estimatedTimeRemaining_ = "";

      message_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.battery.BatteryStorageProto.internal_static_battery_BatteryMonitoringResponse_descriptor;
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryMonitoringResponse getDefaultInstanceForType() {
      return com.smarthome.battery.BatteryMonitoringResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryMonitoringResponse build() {
      com.smarthome.battery.BatteryMonitoringResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.battery.BatteryMonitoringResponse buildPartial() {
      com.smarthome.battery.BatteryMonitoringResponse result = new com.smarthome.battery.BatteryMonitoringResponse(this);
      if (batteryInfoBuilder_ == null) {
        result.batteryInfo_ = batteryInfo_;
      } else {
        result.batteryInfo_ = batteryInfoBuilder_.build();
      }
      result.estimatedTimeRemaining_ = estimatedTimeRemaining_;
      result.message_ = message_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.battery.BatteryMonitoringResponse) {
        return mergeFrom((com.smarthome.battery.BatteryMonitoringResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.battery.BatteryMonitoringResponse other) {
      if (other == com.smarthome.battery.BatteryMonitoringResponse.getDefaultInstance()) return this;
      if (other.hasBatteryInfo()) {
        mergeBatteryInfo(other.getBatteryInfo());
      }
      if (!other.getEstimatedTimeRemaining().isEmpty()) {
        estimatedTimeRemaining_ = other.estimatedTimeRemaining_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.battery.BatteryMonitoringResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.battery.BatteryMonitoringResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.smarthome.battery.BatteryStatusInfo batteryInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.smarthome.battery.BatteryStatusInfo, com.smarthome.battery.BatteryStatusInfo.Builder, com.smarthome.battery.BatteryStatusInfoOrBuilder> batteryInfoBuilder_;
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public boolean hasBatteryInfo() {
      return batteryInfoBuilder_ != null || batteryInfo_ != null;
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public com.smarthome.battery.BatteryStatusInfo getBatteryInfo() {
      if (batteryInfoBuilder_ == null) {
        return batteryInfo_ == null ? com.smarthome.battery.BatteryStatusInfo.getDefaultInstance() : batteryInfo_;
      } else {
        return batteryInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public Builder setBatteryInfo(com.smarthome.battery.BatteryStatusInfo value) {
      if (batteryInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        batteryInfo_ = value;
        onChanged();
      } else {
        batteryInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public Builder setBatteryInfo(
        com.smarthome.battery.BatteryStatusInfo.Builder builderForValue) {
      if (batteryInfoBuilder_ == null) {
        batteryInfo_ = builderForValue.build();
        onChanged();
      } else {
        batteryInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public Builder mergeBatteryInfo(com.smarthome.battery.BatteryStatusInfo value) {
      if (batteryInfoBuilder_ == null) {
        if (batteryInfo_ != null) {
          batteryInfo_ =
            com.smarthome.battery.BatteryStatusInfo.newBuilder(batteryInfo_).mergeFrom(value).buildPartial();
        } else {
          batteryInfo_ = value;
        }
        onChanged();
      } else {
        batteryInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public Builder clearBatteryInfo() {
      if (batteryInfoBuilder_ == null) {
        batteryInfo_ = null;
        onChanged();
      } else {
        batteryInfo_ = null;
        batteryInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public com.smarthome.battery.BatteryStatusInfo.Builder getBatteryInfoBuilder() {
      
      onChanged();
      return getBatteryInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    public com.smarthome.battery.BatteryStatusInfoOrBuilder getBatteryInfoOrBuilder() {
      if (batteryInfoBuilder_ != null) {
        return batteryInfoBuilder_.getMessageOrBuilder();
      } else {
        return batteryInfo_ == null ?
            com.smarthome.battery.BatteryStatusInfo.getDefaultInstance() : batteryInfo_;
      }
    }
    /**
     * <pre>
     * Current battery information.
     * </pre>
     *
     * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.smarthome.battery.BatteryStatusInfo, com.smarthome.battery.BatteryStatusInfo.Builder, com.smarthome.battery.BatteryStatusInfoOrBuilder> 
        getBatteryInfoFieldBuilder() {
      if (batteryInfoBuilder_ == null) {
        batteryInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.smarthome.battery.BatteryStatusInfo, com.smarthome.battery.BatteryStatusInfo.Builder, com.smarthome.battery.BatteryStatusInfoOrBuilder>(
                getBatteryInfo(),
                getParentForChildren(),
                isClean());
        batteryInfo_ = null;
      }
      return batteryInfoBuilder_;
    }

    private java.lang.Object estimatedTimeRemaining_ = "";
    /**
     * <pre>
     * Estimated remaining charging/discharging time.
     * </pre>
     *
     * <code>string estimatedTimeRemaining = 2;</code>
     */
    public java.lang.String getEstimatedTimeRemaining() {
      java.lang.Object ref = estimatedTimeRemaining_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        estimatedTimeRemaining_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Estimated remaining charging/discharging time.
     * </pre>
     *
     * <code>string estimatedTimeRemaining = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEstimatedTimeRemainingBytes() {
      java.lang.Object ref = estimatedTimeRemaining_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        estimatedTimeRemaining_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Estimated remaining charging/discharging time.
     * </pre>
     *
     * <code>string estimatedTimeRemaining = 2;</code>
     */
    public Builder setEstimatedTimeRemaining(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      estimatedTimeRemaining_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Estimated remaining charging/discharging time.
     * </pre>
     *
     * <code>string estimatedTimeRemaining = 2;</code>
     */
    public Builder clearEstimatedTimeRemaining() {
      
      estimatedTimeRemaining_ = getDefaultInstance().getEstimatedTimeRemaining();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Estimated remaining charging/discharging time.
     * </pre>
     *
     * <code>string estimatedTimeRemaining = 2;</code>
     */
    public Builder setEstimatedTimeRemainingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      estimatedTimeRemaining_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * Informational message describing the latest battery event (e.g. "Battery fully charged").
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Informational message describing the latest battery event (e.g. "Battery fully charged").
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Informational message describing the latest battery event (e.g. "Battery fully charged").
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Informational message describing the latest battery event (e.g. "Battery fully charged").
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Informational message describing the latest battery event (e.g. "Battery fully charged").
     * </pre>
     *
     * <code>string message = 3;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:battery.BatteryMonitoringResponse)
  }

  // @@protoc_insertion_point(class_scope:battery.BatteryMonitoringResponse)
  private static final com.smarthome.battery.BatteryMonitoringResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.battery.BatteryMonitoringResponse();
  }

  public static com.smarthome.battery.BatteryMonitoringResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatteryMonitoringResponse>
      PARSER = new com.google.protobuf.AbstractParser<BatteryMonitoringResponse>() {
    @java.lang.Override
    public BatteryMonitoringResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatteryMonitoringResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatteryMonitoringResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatteryMonitoringResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.battery.BatteryMonitoringResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

