// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

public interface BatteryStatusInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:battery.BatteryStatusInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Battery identifier.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  java.lang.String getBatteryId();
  /**
   * <pre>
   * Battery identifier.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatteryIdBytes();

  /**
   * <pre>
   * Current battery level (percentage).
   * </pre>
   *
   * <code>int32 batteryLevel = 2;</code>
   */
  int getBatteryLevel();

  /**
   * <pre>
   * Current charging status.
   * </pre>
   *
   * <code>.battery.ChargingStatus chargingStatus = 3;</code>
   */
  int getChargingStatusValue();
  /**
   * <pre>
   * Current charging status.
   * </pre>
   *
   * <code>.battery.ChargingStatus chargingStatus = 3;</code>
   */
  com.smarthome.battery.ChargingStatus getChargingStatus();

  /**
   * <pre>
   * Current operating mode.
   * </pre>
   *
   * <code>.battery.BatteryMode currentMode = 4;</code>
   */
  int getCurrentModeValue();
  /**
   * <pre>
   * Current operating mode.
   * </pre>
   *
   * <code>.battery.BatteryMode currentMode = 4;</code>
   */
  com.smarthome.battery.BatteryMode getCurrentMode();
}
