// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

/**
 * Protobuf enum {@code battery.BatteryCommand}
 */
public enum BatteryCommand
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>START = 0;</code>
   */
  START(0),
  /**
   * <code>CHANGE_MODE = 1;</code>
   */
  CHANGE_MODE(1),
  /**
   * <code>STOP = 2;</code>
   */
  STOP(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>START = 0;</code>
   */
  public static final int START_VALUE = 0;
  /**
   * <code>CHANGE_MODE = 1;</code>
   */
  public static final int CHANGE_MODE_VALUE = 1;
  /**
   * <code>STOP = 2;</code>
   */
  public static final int STOP_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static BatteryCommand valueOf(int value) {
    return forNumber(value);
  }

  public static BatteryCommand forNumber(int value) {
    switch (value) {
      case 0: return START;
      case 1: return CHANGE_MODE;
      case 2: return STOP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<BatteryCommand>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      BatteryCommand> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<BatteryCommand>() {
          public BatteryCommand findValueByNumber(int number) {
            return BatteryCommand.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.smarthome.battery.BatteryStorageProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final BatteryCommand[] VALUES = values();

  public static BatteryCommand valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private BatteryCommand(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:battery.BatteryCommand)
}

