// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

public final class BatteryStorageProto {
  private BatteryStorageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_battery_GetBatteryStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_battery_GetBatteryStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_battery_BatteryMonitoringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_battery_BatteryMonitoringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_battery_BatteryStatusInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_battery_BatteryStatusInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_battery_BatteryMonitoringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_battery_BatteryMonitoringResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbattery.proto\022\007battery\",\n\027GetBatterySt" +
      "atusRequest\022\021\n\tbatteryId\030\001 \001(\t\"{\n\030Batter" +
      "yMonitoringRequest\022\021\n\tbatteryId\030\001 \001(\t\022(\n" +
      "\007command\030\002 \001(\0162\027.battery.BatteryCommand\022" +
      "\"\n\004mode\030\003 \001(\0162\024.battery.BatteryMode\"\230\001\n\021" +
      "BatteryStatusInfo\022\021\n\tbatteryId\030\001 \001(\t\022\024\n\014" +
      "batteryLevel\030\002 \001(\005\022/\n\016chargingStatus\030\003 \001" +
      "(\0162\027.battery.ChargingStatus\022)\n\013currentMo" +
      "de\030\004 \001(\0162\024.battery.BatteryMode\"}\n\031Batter" +
      "yMonitoringResponse\022/\n\013batteryInfo\030\001 \001(\013" +
      "2\032.battery.BatteryStatusInfo\022\036\n\026estimate" +
      "dTimeRemaining\030\002 \001(\t\022\017\n\007message\030\003 \001(\t*O\n" +
      "\016ChargingStatus\022\013\n\007UNKNOWN\020\000\022\014\n\010CHARGING" +
      "\020\001\022\017\n\013DISCHARGING\020\002\022\010\n\004FULL\020\003\022\007\n\003LOW\020\004*3" +
      "\n\013BatteryMode\022\n\n\006NORMAL\020\000\022\007\n\003ECO\020\001\022\017\n\013PE" +
      "RFORMANCE\020\002*6\n\016BatteryCommand\022\t\n\005START\020\000" +
      "\022\017\n\013CHANGE_MODE\020\001\022\010\n\004STOP\020\0022\314\001\n\025BatteryS" +
      "torageService\022P\n\020GetBatteryStatus\022 .batt" +
      "ery.GetBatteryStatusRequest\032\032.battery.Ba" +
      "tteryStatusInfo\022a\n\024MonitorBatteryStatus\022" +
      "!.battery.BatteryMonitoringRequest\032\".bat" +
      "tery.BatteryMonitoringResponse(\0010\001B.\n\025co" +
      "m.smarthome.batteryB\023BatteryStorageProto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_battery_GetBatteryStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_battery_GetBatteryStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_battery_GetBatteryStatusRequest_descriptor,
        new java.lang.String[] { "BatteryId", });
    internal_static_battery_BatteryMonitoringRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_battery_BatteryMonitoringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_battery_BatteryMonitoringRequest_descriptor,
        new java.lang.String[] { "BatteryId", "Command", "Mode", });
    internal_static_battery_BatteryStatusInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_battery_BatteryStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_battery_BatteryStatusInfo_descriptor,
        new java.lang.String[] { "BatteryId", "BatteryLevel", "ChargingStatus", "CurrentMode", });
    internal_static_battery_BatteryMonitoringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_battery_BatteryMonitoringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_battery_BatteryMonitoringResponse_descriptor,
        new java.lang.String[] { "BatteryInfo", "EstimatedTimeRemaining", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
