// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

public interface BatteryMonitoringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:battery.BatteryMonitoringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Current battery information.
   * </pre>
   *
   * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
   */
  boolean hasBatteryInfo();
  /**
   * <pre>
   * Current battery information.
   * </pre>
   *
   * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
   */
  com.smarthome.battery.BatteryStatusInfo getBatteryInfo();
  /**
   * <pre>
   * Current battery information.
   * </pre>
   *
   * <code>.battery.BatteryStatusInfo batteryInfo = 1;</code>
   */
  com.smarthome.battery.BatteryStatusInfoOrBuilder getBatteryInfoOrBuilder();

  /**
   * <pre>
   * Estimated remaining charging/discharging time.
   * </pre>
   *
   * <code>string estimatedTimeRemaining = 2;</code>
   */
  java.lang.String getEstimatedTimeRemaining();
  /**
   * <pre>
   * Estimated remaining charging/discharging time.
   * </pre>
   *
   * <code>string estimatedTimeRemaining = 2;</code>
   */
  com.google.protobuf.ByteString
      getEstimatedTimeRemainingBytes();

  /**
   * <pre>
   * Informational message describing the latest battery event (e.g. "Battery fully charged").
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Informational message describing the latest battery event (e.g. "Battery fully charged").
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
