// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

/**
 * Protobuf enum {@code battery.ChargingStatus}
 */
public enum ChargingStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>CHARGING = 1;</code>
   */
  CHARGING(1),
  /**
   * <code>DISCHARGING = 2;</code>
   */
  DISCHARGING(2),
  /**
   * <code>FULL = 3;</code>
   */
  FULL(3),
  /**
   * <code>LOW = 4;</code>
   */
  LOW(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>CHARGING = 1;</code>
   */
  public static final int CHARGING_VALUE = 1;
  /**
   * <code>DISCHARGING = 2;</code>
   */
  public static final int DISCHARGING_VALUE = 2;
  /**
   * <code>FULL = 3;</code>
   */
  public static final int FULL_VALUE = 3;
  /**
   * <code>LOW = 4;</code>
   */
  public static final int LOW_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChargingStatus valueOf(int value) {
    return forNumber(value);
  }

  public static ChargingStatus forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return CHARGING;
      case 2: return DISCHARGING;
      case 3: return FULL;
      case 4: return LOW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChargingStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChargingStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChargingStatus>() {
          public ChargingStatus findValueByNumber(int number) {
            return ChargingStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.smarthome.battery.BatteryStorageProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ChargingStatus[] VALUES = values();

  public static ChargingStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChargingStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:battery.ChargingStatus)
}

