// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battery.proto

package com.smarthome.battery;

public interface GetBatteryStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:battery.GetBatteryStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique battery identifier.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  java.lang.String getBatteryId();
  /**
   * <pre>
   * Unique battery identifier.
   * </pre>
   *
   * <code>string batteryId = 1;</code>
   */
  com.google.protobuf.ByteString
      getBatteryIdBytes();
}
