// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solar.proto

package com.smarthome.solar;

/**
 * Protobuf type {@code solar.GetCurrentProductionRequest}
 */
public  final class GetCurrentProductionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:solar.GetCurrentProductionRequest)
    GetCurrentProductionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetCurrentProductionRequest.newBuilder() to construct.
  private GetCurrentProductionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetCurrentProductionRequest() {
    panelId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetCurrentProductionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            panelId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.solar.SolarPanelProto.internal_static_solar_GetCurrentProductionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.solar.SolarPanelProto.internal_static_solar_GetCurrentProductionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.solar.GetCurrentProductionRequest.class, com.smarthome.solar.GetCurrentProductionRequest.Builder.class);
  }

  public static final int PANELID_FIELD_NUMBER = 1;
  private volatile java.lang.Object panelId_;
  /**
   * <pre>
   * Unique identifier of the solar panel.
   * </pre>
   *
   * <code>string panelId = 1;</code>
   */
  public java.lang.String getPanelId() {
    java.lang.Object ref = panelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      panelId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier of the solar panel.
   * </pre>
   *
   * <code>string panelId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPanelIdBytes() {
    java.lang.Object ref = panelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      panelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPanelIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, panelId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPanelIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, panelId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.solar.GetCurrentProductionRequest)) {
      return super.equals(obj);
    }
    com.smarthome.solar.GetCurrentProductionRequest other = (com.smarthome.solar.GetCurrentProductionRequest) obj;

    boolean result = true;
    result = result && getPanelId()
        .equals(other.getPanelId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PANELID_FIELD_NUMBER;
    hash = (53 * hash) + getPanelId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.solar.GetCurrentProductionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.solar.GetCurrentProductionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code solar.GetCurrentProductionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:solar.GetCurrentProductionRequest)
      com.smarthome.solar.GetCurrentProductionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.solar.SolarPanelProto.internal_static_solar_GetCurrentProductionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.solar.SolarPanelProto.internal_static_solar_GetCurrentProductionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.solar.GetCurrentProductionRequest.class, com.smarthome.solar.GetCurrentProductionRequest.Builder.class);
    }

    // Construct using com.smarthome.solar.GetCurrentProductionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      panelId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.solar.SolarPanelProto.internal_static_solar_GetCurrentProductionRequest_descriptor;
    }

    @java.lang.Override
    public com.smarthome.solar.GetCurrentProductionRequest getDefaultInstanceForType() {
      return com.smarthome.solar.GetCurrentProductionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.solar.GetCurrentProductionRequest build() {
      com.smarthome.solar.GetCurrentProductionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.solar.GetCurrentProductionRequest buildPartial() {
      com.smarthome.solar.GetCurrentProductionRequest result = new com.smarthome.solar.GetCurrentProductionRequest(this);
      result.panelId_ = panelId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.solar.GetCurrentProductionRequest) {
        return mergeFrom((com.smarthome.solar.GetCurrentProductionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.solar.GetCurrentProductionRequest other) {
      if (other == com.smarthome.solar.GetCurrentProductionRequest.getDefaultInstance()) return this;
      if (!other.getPanelId().isEmpty()) {
        panelId_ = other.panelId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.solar.GetCurrentProductionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.solar.GetCurrentProductionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object panelId_ = "";
    /**
     * <pre>
     * Unique identifier of the solar panel.
     * </pre>
     *
     * <code>string panelId = 1;</code>
     */
    public java.lang.String getPanelId() {
      java.lang.Object ref = panelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        panelId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier of the solar panel.
     * </pre>
     *
     * <code>string panelId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPanelIdBytes() {
      java.lang.Object ref = panelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        panelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier of the solar panel.
     * </pre>
     *
     * <code>string panelId = 1;</code>
     */
    public Builder setPanelId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      panelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier of the solar panel.
     * </pre>
     *
     * <code>string panelId = 1;</code>
     */
    public Builder clearPanelId() {
      
      panelId_ = getDefaultInstance().getPanelId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier of the solar panel.
     * </pre>
     *
     * <code>string panelId = 1;</code>
     */
    public Builder setPanelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      panelId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:solar.GetCurrentProductionRequest)
  }

  // @@protoc_insertion_point(class_scope:solar.GetCurrentProductionRequest)
  private static final com.smarthome.solar.GetCurrentProductionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.solar.GetCurrentProductionRequest();
  }

  public static com.smarthome.solar.GetCurrentProductionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetCurrentProductionRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetCurrentProductionRequest>() {
    @java.lang.Override
    public GetCurrentProductionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetCurrentProductionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetCurrentProductionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetCurrentProductionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.solar.GetCurrentProductionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

