// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solar.proto

package com.smarthome.solar;

public interface GetCurrentProductionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solar.GetCurrentProductionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier of the solar panel.
   * </pre>
   *
   * <code>string panelId = 1;</code>
   */
  java.lang.String getPanelId();
  /**
   * <pre>
   * Unique identifier of the solar panel.
   * </pre>
   *
   * <code>string panelId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPanelIdBytes();
}
