// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solar.proto

package com.smarthome.solar;

public interface ProductionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:solar.ProductionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier of the solar panel.
   * </pre>
   *
   * <code>string panelId = 1;</code>
   */
  java.lang.String getPanelId();
  /**
   * <pre>
   * Unique identifier of the solar panel.
   * </pre>
   *
   * <code>string panelId = 1;</code>
   */
  com.google.protobuf.ByteString
      getPanelIdBytes();

  /**
   * <pre>
   * Current energy production.
   * </pre>
   *
   * <code>double currentProduction = 2;</code>
   */
  double getCurrentProduction();

  /**
   * <pre>
   * Unit of measurement.
   * </pre>
   *
   * <code>string unit = 3;</code>
   */
  java.lang.String getUnit();
  /**
   * <pre>
   * Unit of measurement.
   * </pre>
   *
   * <code>string unit = 3;</code>
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <pre>
   * Timestamp representing when the measurement was taken.
   * </pre>
   *
   * <code>string timestamp = 4;</code>
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * Timestamp representing when the measurement was taken.
   * </pre>
   *
   * <code>string timestamp = 4;</code>
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
