// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: solar.proto

package com.smarthome.solar;

public final class SolarPanelProto {
  private SolarPanelProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solar_GetCurrentProductionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solar_GetCurrentProductionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solar_MonitorProductionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solar_MonitorProductionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solar_ProductionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solar_ProductionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013solar.proto\022\005solar\".\n\033GetCurrentProduc" +
      "tionRequest\022\017\n\007panelId\030\001 \001(\t\"+\n\030MonitorP" +
      "roductionRequest\022\017\n\007panelId\030\001 \001(\t\"]\n\016Pro" +
      "ductionInfo\022\017\n\007panelId\030\001 \001(\t\022\031\n\021currentP" +
      "roduction\030\002 \001(\001\022\014\n\004unit\030\003 \001(\t\022\021\n\ttimesta" +
      "mp\030\004 \001(\t2\265\001\n\021SolarPanelService\022Q\n\024GetCur" +
      "rentProduction\022\".solar.GetCurrentProduct" +
      "ionRequest\032\025.solar.ProductionInfo\022M\n\021Mon" +
      "itorProduction\022\037.solar.MonitorProduction" +
      "Request\032\025.solar.ProductionInfo0\001B(\n\023com." +
      "smarthome.solarB\017SolarPanelProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_solar_GetCurrentProductionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_solar_GetCurrentProductionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solar_GetCurrentProductionRequest_descriptor,
        new java.lang.String[] { "PanelId", });
    internal_static_solar_MonitorProductionRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_solar_MonitorProductionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solar_MonitorProductionRequest_descriptor,
        new java.lang.String[] { "PanelId", });
    internal_static_solar_ProductionInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_solar_ProductionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solar_ProductionInfo_descriptor,
        new java.lang.String[] { "PanelId", "CurrentProduction", "Unit", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
