// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

/**
 * Protobuf type {@code smartmeter.ConsumptionSummary}
 */
public  final class ConsumptionSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartmeter.ConsumptionSummary)
    ConsumptionSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConsumptionSummary.newBuilder() to construct.
  private ConsumptionSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConsumptionSummary() {
    highestConsumer_ = "";
    highestConsumption_ = 0;
    totalConsumption_ = 0;
    averageConsumption_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConsumptionSummary(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            highestConsumer_ = s;
            break;
          }
          case 16: {

            highestConsumption_ = input.readInt32();
            break;
          }
          case 24: {

            totalConsumption_ = input.readInt32();
            break;
          }
          case 33: {

            averageConsumption_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_ConsumptionSummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_ConsumptionSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.smartmeter.ConsumptionSummary.class, com.smarthome.smartmeter.ConsumptionSummary.Builder.class);
  }

  public static final int HIGHESTCONSUMER_FIELD_NUMBER = 1;
  private volatile java.lang.Object highestConsumer_;
  /**
   * <pre>
   * Appliance with the highest energy consumption.
   * </pre>
   *
   * <code>string highestConsumer = 1;</code>
   */
  public java.lang.String getHighestConsumer() {
    java.lang.Object ref = highestConsumer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      highestConsumer_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Appliance with the highest energy consumption.
   * </pre>
   *
   * <code>string highestConsumer = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHighestConsumerBytes() {
    java.lang.Object ref = highestConsumer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      highestConsumer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIGHESTCONSUMPTION_FIELD_NUMBER = 2;
  private int highestConsumption_;
  /**
   * <pre>
   * Consumption of the highest consumer.
   * </pre>
   *
   * <code>int32 highestConsumption = 2;</code>
   */
  public int getHighestConsumption() {
    return highestConsumption_;
  }

  public static final int TOTALCONSUMPTION_FIELD_NUMBER = 3;
  private int totalConsumption_;
  /**
   * <pre>
   * Total energy consumption of all uploaded appliances.
   * </pre>
   *
   * <code>int32 totalConsumption = 3;</code>
   */
  public int getTotalConsumption() {
    return totalConsumption_;
  }

  public static final int AVERAGECONSUMPTION_FIELD_NUMBER = 4;
  private double averageConsumption_;
  /**
   * <pre>
   * Average consumption considering all uploaded appliances.
   * </pre>
   *
   * <code>double averageConsumption = 4;</code>
   */
  public double getAverageConsumption() {
    return averageConsumption_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHighestConsumerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, highestConsumer_);
    }
    if (highestConsumption_ != 0) {
      output.writeInt32(2, highestConsumption_);
    }
    if (totalConsumption_ != 0) {
      output.writeInt32(3, totalConsumption_);
    }
    if (averageConsumption_ != 0D) {
      output.writeDouble(4, averageConsumption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHighestConsumerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, highestConsumer_);
    }
    if (highestConsumption_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, highestConsumption_);
    }
    if (totalConsumption_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalConsumption_);
    }
    if (averageConsumption_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, averageConsumption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.smartmeter.ConsumptionSummary)) {
      return super.equals(obj);
    }
    com.smarthome.smartmeter.ConsumptionSummary other = (com.smarthome.smartmeter.ConsumptionSummary) obj;

    boolean result = true;
    result = result && getHighestConsumer()
        .equals(other.getHighestConsumer());
    result = result && (getHighestConsumption()
        == other.getHighestConsumption());
    result = result && (getTotalConsumption()
        == other.getTotalConsumption());
    result = result && (
        java.lang.Double.doubleToLongBits(getAverageConsumption())
        == java.lang.Double.doubleToLongBits(
            other.getAverageConsumption()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HIGHESTCONSUMER_FIELD_NUMBER;
    hash = (53 * hash) + getHighestConsumer().hashCode();
    hash = (37 * hash) + HIGHESTCONSUMPTION_FIELD_NUMBER;
    hash = (53 * hash) + getHighestConsumption();
    hash = (37 * hash) + TOTALCONSUMPTION_FIELD_NUMBER;
    hash = (53 * hash) + getTotalConsumption();
    hash = (37 * hash) + AVERAGECONSUMPTION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAverageConsumption()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.smartmeter.ConsumptionSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.smartmeter.ConsumptionSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartmeter.ConsumptionSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartmeter.ConsumptionSummary)
      com.smarthome.smartmeter.ConsumptionSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_ConsumptionSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_ConsumptionSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.smartmeter.ConsumptionSummary.class, com.smarthome.smartmeter.ConsumptionSummary.Builder.class);
    }

    // Construct using com.smarthome.smartmeter.ConsumptionSummary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      highestConsumer_ = "";

      highestConsumption_ = 0;

      totalConsumption_ = 0;

      averageConsumption_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_ConsumptionSummary_descriptor;
    }

    @java.lang.Override
    public com.smarthome.smartmeter.ConsumptionSummary getDefaultInstanceForType() {
      return com.smarthome.smartmeter.ConsumptionSummary.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.smartmeter.ConsumptionSummary build() {
      com.smarthome.smartmeter.ConsumptionSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.smartmeter.ConsumptionSummary buildPartial() {
      com.smarthome.smartmeter.ConsumptionSummary result = new com.smarthome.smartmeter.ConsumptionSummary(this);
      result.highestConsumer_ = highestConsumer_;
      result.highestConsumption_ = highestConsumption_;
      result.totalConsumption_ = totalConsumption_;
      result.averageConsumption_ = averageConsumption_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.smartmeter.ConsumptionSummary) {
        return mergeFrom((com.smarthome.smartmeter.ConsumptionSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.smartmeter.ConsumptionSummary other) {
      if (other == com.smarthome.smartmeter.ConsumptionSummary.getDefaultInstance()) return this;
      if (!other.getHighestConsumer().isEmpty()) {
        highestConsumer_ = other.highestConsumer_;
        onChanged();
      }
      if (other.getHighestConsumption() != 0) {
        setHighestConsumption(other.getHighestConsumption());
      }
      if (other.getTotalConsumption() != 0) {
        setTotalConsumption(other.getTotalConsumption());
      }
      if (other.getAverageConsumption() != 0D) {
        setAverageConsumption(other.getAverageConsumption());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.smartmeter.ConsumptionSummary parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.smartmeter.ConsumptionSummary) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object highestConsumer_ = "";
    /**
     * <pre>
     * Appliance with the highest energy consumption.
     * </pre>
     *
     * <code>string highestConsumer = 1;</code>
     */
    public java.lang.String getHighestConsumer() {
      java.lang.Object ref = highestConsumer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        highestConsumer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Appliance with the highest energy consumption.
     * </pre>
     *
     * <code>string highestConsumer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHighestConsumerBytes() {
      java.lang.Object ref = highestConsumer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        highestConsumer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Appliance with the highest energy consumption.
     * </pre>
     *
     * <code>string highestConsumer = 1;</code>
     */
    public Builder setHighestConsumer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      highestConsumer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Appliance with the highest energy consumption.
     * </pre>
     *
     * <code>string highestConsumer = 1;</code>
     */
    public Builder clearHighestConsumer() {
      
      highestConsumer_ = getDefaultInstance().getHighestConsumer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Appliance with the highest energy consumption.
     * </pre>
     *
     * <code>string highestConsumer = 1;</code>
     */
    public Builder setHighestConsumerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      highestConsumer_ = value;
      onChanged();
      return this;
    }

    private int highestConsumption_ ;
    /**
     * <pre>
     * Consumption of the highest consumer.
     * </pre>
     *
     * <code>int32 highestConsumption = 2;</code>
     */
    public int getHighestConsumption() {
      return highestConsumption_;
    }
    /**
     * <pre>
     * Consumption of the highest consumer.
     * </pre>
     *
     * <code>int32 highestConsumption = 2;</code>
     */
    public Builder setHighestConsumption(int value) {
      
      highestConsumption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Consumption of the highest consumer.
     * </pre>
     *
     * <code>int32 highestConsumption = 2;</code>
     */
    public Builder clearHighestConsumption() {
      
      highestConsumption_ = 0;
      onChanged();
      return this;
    }

    private int totalConsumption_ ;
    /**
     * <pre>
     * Total energy consumption of all uploaded appliances.
     * </pre>
     *
     * <code>int32 totalConsumption = 3;</code>
     */
    public int getTotalConsumption() {
      return totalConsumption_;
    }
    /**
     * <pre>
     * Total energy consumption of all uploaded appliances.
     * </pre>
     *
     * <code>int32 totalConsumption = 3;</code>
     */
    public Builder setTotalConsumption(int value) {
      
      totalConsumption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total energy consumption of all uploaded appliances.
     * </pre>
     *
     * <code>int32 totalConsumption = 3;</code>
     */
    public Builder clearTotalConsumption() {
      
      totalConsumption_ = 0;
      onChanged();
      return this;
    }

    private double averageConsumption_ ;
    /**
     * <pre>
     * Average consumption considering all uploaded appliances.
     * </pre>
     *
     * <code>double averageConsumption = 4;</code>
     */
    public double getAverageConsumption() {
      return averageConsumption_;
    }
    /**
     * <pre>
     * Average consumption considering all uploaded appliances.
     * </pre>
     *
     * <code>double averageConsumption = 4;</code>
     */
    public Builder setAverageConsumption(double value) {
      
      averageConsumption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Average consumption considering all uploaded appliances.
     * </pre>
     *
     * <code>double averageConsumption = 4;</code>
     */
    public Builder clearAverageConsumption() {
      
      averageConsumption_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartmeter.ConsumptionSummary)
  }

  // @@protoc_insertion_point(class_scope:smartmeter.ConsumptionSummary)
  private static final com.smarthome.smartmeter.ConsumptionSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.smartmeter.ConsumptionSummary();
  }

  public static com.smarthome.smartmeter.ConsumptionSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConsumptionSummary>
      PARSER = new com.google.protobuf.AbstractParser<ConsumptionSummary>() {
    @java.lang.Override
    public ConsumptionSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConsumptionSummary(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConsumptionSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConsumptionSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.smartmeter.ConsumptionSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

