// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

public interface ConsumptionSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartmeter.ConsumptionSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Appliance with the highest energy consumption.
   * </pre>
   *
   * <code>string highestConsumer = 1;</code>
   */
  java.lang.String getHighestConsumer();
  /**
   * <pre>
   * Appliance with the highest energy consumption.
   * </pre>
   *
   * <code>string highestConsumer = 1;</code>
   */
  com.google.protobuf.ByteString
      getHighestConsumerBytes();

  /**
   * <pre>
   * Consumption of the highest consumer.
   * </pre>
   *
   * <code>int32 highestConsumption = 2;</code>
   */
  int getHighestConsumption();

  /**
   * <pre>
   * Total energy consumption of all uploaded appliances.
   * </pre>
   *
   * <code>int32 totalConsumption = 3;</code>
   */
  int getTotalConsumption();

  /**
   * <pre>
   * Average consumption considering all uploaded appliances.
   * </pre>
   *
   * <code>double averageConsumption = 4;</code>
   */
  double getAverageConsumption();
}
