// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

public interface ConsumptionReadingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartmeter.ConsumptionReading)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the appliance.
   * </pre>
   *
   * <code>string device = 1;</code>
   */
  java.lang.String getDevice();
  /**
   * <pre>
   * Name of the appliance.
   * </pre>
   *
   * <code>string device = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <pre>
   * Power consumption in watts.
   * </pre>
   *
   * <code>int32 consumption = 2;</code>
   */
  int getConsumption();
}
