// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

public interface GenerateEnergyReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartmeter.GenerateEnergyReportRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier of the house.
   * </pre>
   *
   * <code>string houseId = 1;</code>
   */
  java.lang.String getHouseId();
  /**
   * <pre>
   * Unique identifier of the house.
   * </pre>
   *
   * <code>string houseId = 1;</code>
   */
  com.google.protobuf.ByteString
      getHouseIdBytes();
}
