// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

/**
 * Protobuf type {@code smartmeter.GenerateEnergyReportRequest}
 */
public  final class GenerateEnergyReportRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartmeter.GenerateEnergyReportRequest)
    GenerateEnergyReportRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GenerateEnergyReportRequest.newBuilder() to construct.
  private GenerateEnergyReportRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GenerateEnergyReportRequest() {
    houseId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GenerateEnergyReportRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            houseId_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_GenerateEnergyReportRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_GenerateEnergyReportRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.smartmeter.GenerateEnergyReportRequest.class, com.smarthome.smartmeter.GenerateEnergyReportRequest.Builder.class);
  }

  public static final int HOUSEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object houseId_;
  /**
   * <pre>
   * Unique identifier of the house.
   * </pre>
   *
   * <code>string houseId = 1;</code>
   */
  public java.lang.String getHouseId() {
    java.lang.Object ref = houseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      houseId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique identifier of the house.
   * </pre>
   *
   * <code>string houseId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHouseIdBytes() {
    java.lang.Object ref = houseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      houseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHouseIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, houseId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHouseIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, houseId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.smartmeter.GenerateEnergyReportRequest)) {
      return super.equals(obj);
    }
    com.smarthome.smartmeter.GenerateEnergyReportRequest other = (com.smarthome.smartmeter.GenerateEnergyReportRequest) obj;

    boolean result = true;
    result = result && getHouseId()
        .equals(other.getHouseId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOUSEID_FIELD_NUMBER;
    hash = (53 * hash) + getHouseId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.smartmeter.GenerateEnergyReportRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.smartmeter.GenerateEnergyReportRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code smartmeter.GenerateEnergyReportRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartmeter.GenerateEnergyReportRequest)
      com.smarthome.smartmeter.GenerateEnergyReportRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_GenerateEnergyReportRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_GenerateEnergyReportRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.smartmeter.GenerateEnergyReportRequest.class, com.smarthome.smartmeter.GenerateEnergyReportRequest.Builder.class);
    }

    // Construct using com.smarthome.smartmeter.GenerateEnergyReportRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      houseId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.smartmeter.SmartMeterProto.internal_static_smartmeter_GenerateEnergyReportRequest_descriptor;
    }

    @java.lang.Override
    public com.smarthome.smartmeter.GenerateEnergyReportRequest getDefaultInstanceForType() {
      return com.smarthome.smartmeter.GenerateEnergyReportRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.smartmeter.GenerateEnergyReportRequest build() {
      com.smarthome.smartmeter.GenerateEnergyReportRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.smartmeter.GenerateEnergyReportRequest buildPartial() {
      com.smarthome.smartmeter.GenerateEnergyReportRequest result = new com.smarthome.smartmeter.GenerateEnergyReportRequest(this);
      result.houseId_ = houseId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.smartmeter.GenerateEnergyReportRequest) {
        return mergeFrom((com.smarthome.smartmeter.GenerateEnergyReportRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.smartmeter.GenerateEnergyReportRequest other) {
      if (other == com.smarthome.smartmeter.GenerateEnergyReportRequest.getDefaultInstance()) return this;
      if (!other.getHouseId().isEmpty()) {
        houseId_ = other.houseId_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.smartmeter.GenerateEnergyReportRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.smartmeter.GenerateEnergyReportRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object houseId_ = "";
    /**
     * <pre>
     * Unique identifier of the house.
     * </pre>
     *
     * <code>string houseId = 1;</code>
     */
    public java.lang.String getHouseId() {
      java.lang.Object ref = houseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        houseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier of the house.
     * </pre>
     *
     * <code>string houseId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHouseIdBytes() {
      java.lang.Object ref = houseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        houseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique identifier of the house.
     * </pre>
     *
     * <code>string houseId = 1;</code>
     */
    public Builder setHouseId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      houseId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier of the house.
     * </pre>
     *
     * <code>string houseId = 1;</code>
     */
    public Builder clearHouseId() {
      
      houseId_ = getDefaultInstance().getHouseId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique identifier of the house.
     * </pre>
     *
     * <code>string houseId = 1;</code>
     */
    public Builder setHouseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      houseId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartmeter.GenerateEnergyReportRequest)
  }

  // @@protoc_insertion_point(class_scope:smartmeter.GenerateEnergyReportRequest)
  private static final com.smarthome.smartmeter.GenerateEnergyReportRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.smartmeter.GenerateEnergyReportRequest();
  }

  public static com.smarthome.smartmeter.GenerateEnergyReportRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenerateEnergyReportRequest>
      PARSER = new com.google.protobuf.AbstractParser<GenerateEnergyReportRequest>() {
    @java.lang.Override
    public GenerateEnergyReportRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GenerateEnergyReportRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GenerateEnergyReportRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenerateEnergyReportRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.smartmeter.GenerateEnergyReportRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

