// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

public interface ReportEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartmeter.ReportEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the report section (e.g. Daily Production, Energy Efficiency, Recommendation etc)
   * </pre>
   *
   * <code>string section = 1;</code>
   */
  java.lang.String getSection();
  /**
   * <pre>
   * Name of the report section (e.g. Daily Production, Energy Efficiency, Recommendation etc)
   * </pre>
   *
   * <code>string section = 1;</code>
   */
  com.google.protobuf.ByteString
      getSectionBytes();

  /**
   * <pre>
   * Value associated with the section (e.g. 24.kWh, 74%, Charging etc).
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Value associated with the section (e.g. 24.kWh, 74%, Charging etc).
   * </pre>
   *
   * <code>string value = 2;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes();

  /**
   * <pre>
   * Additional explanation shown to the user (e.g. "Reduce unnecessary consumption during peak hours.").
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Additional explanation shown to the user (e.g. "Reduce unnecessary consumption during peak hours.").
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
