// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartmeter.proto

package com.smarthome.smartmeter;

public final class SmartMeterProto {
  private SmartMeterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartmeter_GenerateEnergyReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartmeter_GenerateEnergyReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartmeter_ReportEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartmeter_ReportEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartmeter_ConsumptionReading_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartmeter_ConsumptionReading_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartmeter_ConsumptionSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartmeter_ConsumptionSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020smartmeter.proto\022\nsmartmeter\".\n\033Genera" +
      "teEnergyReportRequest\022\017\n\007houseId\030\001 \001(\t\"B" +
      "\n\013ReportEntry\022\017\n\007section\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t\022\023\n\013description\030\003 \001(\t\"9\n\022Consumptio" +
      "nReading\022\016\n\006device\030\001 \001(\t\022\023\n\013consumption\030" +
      "\002 \001(\005\"\177\n\022ConsumptionSummary\022\027\n\017highestCo" +
      "nsumer\030\001 \001(\t\022\032\n\022highestConsumption\030\002 \001(\005" +
      "\022\030\n\020totalConsumption\030\003 \001(\005\022\032\n\022averageCon" +
      "sumption\030\004 \001(\0012\316\001\n\021SmartMeterService\022Z\n\024" +
      "GenerateEnergyReport\022\'.smartmeter.Genera" +
      "teEnergyReportRequest\032\027.smartmeter.Repor" +
      "tEntry0\001\022]\n\031UploadConsumptionReadings\022\036." +
      "smartmeter.ConsumptionReading\032\036.smartmet" +
      "er.ConsumptionSummary(\001B-\n\030com.smarthome" +
      ".smartmeterB\017SmartMeterProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartmeter_GenerateEnergyReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartmeter_GenerateEnergyReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartmeter_GenerateEnergyReportRequest_descriptor,
        new java.lang.String[] { "HouseId", });
    internal_static_smartmeter_ReportEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartmeter_ReportEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartmeter_ReportEntry_descriptor,
        new java.lang.String[] { "Section", "Value", "Description", });
    internal_static_smartmeter_ConsumptionReading_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartmeter_ConsumptionReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartmeter_ConsumptionReading_descriptor,
        new java.lang.String[] { "Device", "Consumption", });
    internal_static_smartmeter_ConsumptionSummary_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartmeter_ConsumptionSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartmeter_ConsumptionSummary_descriptor,
        new java.lang.String[] { "HighestConsumer", "HighestConsumption", "TotalConsumption", "AverageConsumption", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
